version: "3.9"

services:
  web:
    build: .
    container_name: belanja-web
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
    env_file:
      - .env
