import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../../globals.css";
import { AppSidebar } from "@/components/app-sidebar";

import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import Header from "./_components/header";
import { getUser } from "@/lib/auth";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { session, user } = await getUser();

  if (!session || user.role !== "superadmin") {
    return redirect("/dashboard/sign-in");
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <SidebarProvider>
          <AppSidebar variant="sidebar" />
          <SidebarInset>
            <Header />
            <main className="p-4">
              <h1>{children}</h1>
            </main>
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
